class Question {
  final int? id, answer;
  final String? question,questionsId;
  final List<dynamic>? options;

  Question({this.id, this.question,this.questionsId, this.answer, this.options});

}
const List allQuestions = [ //map list
  {
    "questionsId": "nk_1",
    "id": 1,
    "question": "12 x 5 = ?",
    "options": ['40', '50', '60', '70'],
    "answer_index": 2
  },
  {
    "questionsId": "nk_1",
    "id": 2,
    "question": "Sıfır hariç en küçük asal sayı nedir?",
    "options": ['1', '2', '3', '5'],
    "answer_index": 1
  },
  {
    "questionsId": "nk_1",
    "id": 3,
    "question": "Karekök(144) kaçtır?",
    "options": ['10', '12', '14', '16'],
    "answer_index": 1
  },
  {
    "questionsId": "nk_1",
    "id": 4,
    "question": "Bir dizi sayının ortalaması bulunurken kullanılan matematiksel işlem hangisidir?",
    "options": ['Toplama', 'Çarpma', 'Bölme', 'Çıkarma'],
    "answer_index": 2
  },
  {
    "questionsId": "nk_1",
    "id": 5,
    "question": "Bir dik üçgenin hipotenüsü 10 birim, bir kenarı 6 birim ise, diğer kenarı kaç birimdir?",
    "options": ['4', '6', '8', '10'],
    "answer_index": 0
  },
  {
    "questionsId": "nk_1",
    "id": 6,
    "question": "2^3 kaçtır?",
    "options": ['4', '6', '8', '16'],
    "answer_index": 2
  },
  {
    "questionsId": "nk_1",
    "id": 7,
    "question": "Bir çemberin çevresini hesaplamak için kullanılan matematiksel sabit nedir?",
    "options": ['π (pi)', 'e', 'φ (altın oran)', '√2'],
    "answer_index": 0
  },
  {
    "questionsId": "nk_1",
    "id": 8,
    "question": "3! (Faktöriyel üç) kaçtır?",
    "options": ['3', '6', '9', '12'],
    "answer_index": 1
  },
  {
    "questionsId": "nk_1",
    "id": 9,
    "question": "Bir silindirin hacmi hesaplanırken kullanılan formül hangisidir?",
    "options": ['V = πr^2h', 'V = (1/3)πr^2h', 'V = (4/3)πr^3', 'V = 2πrh'],
    "answer_index": 0
  },
  {
    "questionsId": "nk_1",
    "id": 10,
    "question": "30'un 10'a bölümü kaçtır?",
    "options": ['2', '3', '4', '5'],
    "answer_index": 3
  },
  {
    "questionsId": "nk_1",
    "id": 11,
    "question": "Bir geometrik şeklin alanını hesaplamak için kullanılan matematiksel sabit nedir?",
    "options": ['π (pi)', 'e', 'φ (altın oran)', '√2'],
    "answer_index": 0
  },
  {
    "questionsId": "nk_1",
    "id": 12,
    "question": "Bir karenin çevresi nasıl hesaplanır?",
    "options": ['P = a^2', 'P = 2a', 'P = 4a', 'P = (1/2)a'],
    "answer_index": 2
  },
  {
    "questionsId": "nk_1",
    "id": 13,
    "question": "Bir zarın üzerindeki rakamların toplamı kaçtır?",
    "options": ['14', '21', '28', '36'],
    "answer_index": 1
  },
  {
    "questionsId": "nk_1",
    "id": 14,
    "question": "Bir açının derece cinsinden ölçüsü 90 ise, bu açının tipi nedir?",
    "options": ['Dik açı', 'Geniş açı', 'Dar açı', 'Tam açı'],
    "answer_index": 0
  },
  {
    "questionsId": "nk_1",
    "id": 15,
    "question": "Bir dairenin alanı hesaplanırken kullanılan matematiksel sabit nedir?",
    "options": ['π (pi)', 'e', 'φ (altın oran)', '√2'],
    "answer_index": 0
  },
  {
    "questionsId": "nk_1",
    "id": 16,
    "question": "Bir futbol takımının sahada kaç oyuncusu vardır?",
    "options": ['9', '10', '11', '12'],
    "answer_index": 2
  },
  {
    "questionsId": "nk_1",
    "id": 17,
    "question": "Bir yıl kaç gün sürer?",
    "options": ['365', '366', '367', '364'],
    "answer_index": 0
  },
  {
    "questionsId": "nk_1",
    "id": 18,
    "question": "10! (Faktöriyel on) kaçtır?",
    "options": ['10', '100', '1000', '3628800'],
    "answer_index": 3
  },
  {
    "questionsId": "nk_1",
    "id": 19,
    "question": "Bir dörtgenin iç açılarının toplamı kaçtır?",
    "options": ['180', '270', '360', '450'],
    "answer_index": 2
  },
  {
    "questionsId": "nk_1",
    "id": 20,
    "question": "3^4 kaçtır?",
    "options": ['9', '12', '27', '81'],
    "answer_index": 3
  },


  {
    "questionsId": "nk_2",
    "id": 1,
    "question": "Aşağıdakilerden hangisi Peygamberlerde “aleyhimüsselâm” bulunan yedi sıfatdan birisi değildir ?",
    "options": ['İsmet', 'Teblig', 'Adalet', 'Metanet'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_2",
    "id": 2,
    "question": "Adem, İdris, Şit ve İbrahim (aleyhimüsselam)a sırasıyla kaçar suhûf gönderilmiştir ?",
    "options": ['10 / 30 / 50 / 10', '10 / 30 / 50 / 1', '5 / 10 / 30 / 50', '10 / 50 / 30 / 10'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_2",
    "id": 3,
    "question": "Azâb meleklerinin büyüklerine, Huzûr-i ilâhîde bulunan meleklere ve rahmet meleklerine sırasıyla ne denir ?",
    "options": ['Kerûbiyân, Mâlik, Mukarrebîn', 'Rûhânîyân, Mukarrebîn, Kerûbiyân', 'Kerûbiyân, Hamele-i Arş, Rûhânîyân', 'Kerûbiyân, Mukarrebîn, Rûhânîyân'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_2",
    "id": 4,
    "question": "Namâz Kitâbı Hakîkat Kitabevi Yayınları’nın kaç numaralı kitabıdır ?",
    "options": ['8', '9', '10', '11'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_2",
    "id": 5,
    "question": "Namaz ile ilgili aşağıda verilen bilgilerden hangisi yanlıştır ?",
    "options": ['Îman etdikden sonra en mühim emr namâzdır', 'Bir vakt namazını kaçıran kişinin affa kavuşması için tövbe etmesi yeterlidir', 'Hanbelî mezhebinde namazı kılmamak küfrdür', 'Namâz kılmak imanın şartı değildir'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_2",
    "id": 6,
    "question": "(Erkeklerin yürüyerek, öksürerek veyâ sol tarafa yatarak (İstibrâ) etmesi, ya’nî idrâr yolunda damlalar bırakmaması ………………….) Boşluğa gelmesi gereken, hangi şıkta doğru olarak verilmiştir ?",
    "options": ['Vâcibdir', 'Sünnetdir', 'Mübahdır', 'Mekruhdur'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_2",
    "id": 7,
    "question": "“Bir kimse bir namazı bile bile öbür namâza birleşdirirse ...... hukbe Cehennemde yanacaktır. Bir hukbe ...... âhiret senesidir. Âhiretin bir günü ...... dünyâ senesidir.” cümlesindeki boşluklara sırayla hangileri gelmelidir ?",
    "options": ['Altmış / yetmiş / iki bin', 'Yetmiş / seksen / üç bin', 'Seksen / seksen / bin', 'Doksan / doksan / bin'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_2",
    "id": 8,
    "question": "Aşağıdakilerden hangisi Ehl-i Sünnet İ’tikâdında olmanın alâmetlerinden değildir ?",
    "options": ['İbadetler, îmândan bir parçadır', 'Müslimânlar, başındaki âmirlerine, idârecilerine isyân etmemelidir', 'Ehli kıble olduklarını söyleyen, yanlış i’tikâtda olanları tekfîr etmemelidir', 'Açıkca günâh işlediği bilinmeyen her imâmın arkasında namaz kılmalıdır'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_2",
    "id": 9,
    "question": " I) Farz, vâcib ve harâm \n II) Sünnet ve mekrûh \n III) Mubâh ve müfsid \n IV) Müstehab \n V) Müfsid ve nâfile \nYukarıdakilerden hangileri Ahkâm-ı İslâmiyye’nin maddelerindendir ?",
    "options": ['I, II, IV, V', 'I, II, III, IV', 'II, III, IV', 'I, II, IV, V'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_2",
    "id": 10,
    "question": "Aşağıdakilerden hangisi 54 farzdan birisi değildir ?",
    "options": ['Şirk koşmamak', 'Kibirli olmaktan sakınmak', 'Kanâ’at etmemek', 'Abdest almak'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_2",
    "id": 11,
    "question": "Aşağıdakilerden hangisi Hanefi mezhebine göre guslün farzlarından birisidir ?",
    "options": ['Tertip', 'Muvalat', 'Delk', 'İstinşak'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_2",
    "id": 12,
    "question": "Bir aylık ramazan orucunun iskatı kaç altındır ?",
    "options": ['1', '5', '10', '40'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_2",
    "id": 13,
    "question": "Hastalıkla namaz mevzusuyla ilgili aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Ayakda duramıyan hasta, namazı oturarak kılar', 'Oturamıyan hasta, namazı yatarak kılar', 'Sandalyede, koltukda oturup ayaklarını sarkıtarak namaz kılmağa izn verilmişdir', 'Cemâ’ate gidince ayakda kılamıyan, evinde ayakda kılar'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_2",
    "id": 14,
    "question": "Aşağıdakilerden hangisi Namaz Kitabında bildirilen 40 kötü huydan birisi değildir ?",
    "options": ['Müslimana kötü isim takmak', 'Mal ve mevkı hırsı', 'Müslimana beddua etmek', 'Yaptığı iyilikleri başa kakmak'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_2",
    "id": 15,
    "question": "Kaza namazları ile ilgili aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Sünnet olan namazı kazâ etmek sünnettir', 'Kaza borcu 6’dan az olana (Tertîb sâhibi) denir', 'Vâcib olan namazı kazâ etmek vâcibdir', 'Farz olan namazı kazâ etmek farzdır'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_2",
    "id": 16,
    "question": "Adak olan namâz ve başlanıp yarıda kalan nâfileler ……… namazlardır. Boşluğa gelmesi gereken ifade hangi şıkta doğru olarak verilmiştir ?",
    "options": ['Farz', 'Sünnet', 'Mübah', 'Vâcib'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_2",
    "id": 17,
    "question": "Halâya girmek için, husûsî şalvar kullanmak ve başı örtülü girmek …………. Boşluğa gelmesi gereken, hangi şıkta doğru olarak verilmiştir ?",
    "options": ['Mübahdır', 'Sünnetdir', 'Müstehabdır', 'Farzdır'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_2",
    "id": 18,
    "question": "Aşağıdaki ifadelerden hangisi doğrudur ?",
    "options": ['Yalnız nafile kılmak için mekruh olan üç vakit vardır', 'Namaz kılması tahrimen mekruh olan vakit ikidir', 'Namaz kılınması haram olan vakitlerde secde-i tilavet yapmak caiz değildir', 'Namaz kılması tahrimen mekruh olan vaktler ikidir'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_2",
    "id": 19,
    "question": "Aşağıdaki ifadelerden hangisi yanlıştır ?",
    "options": ['Fâtihayı sûreden önce okumak sünnettir', 'Sünnetlerin ve vitrin her rek’atinde Kur’ân-ı kerîmden bir âyet okumak farzdır', 'Namâzın içindeki farzlarına (Rükn) denir', 'Kırâetde, Kur’ân-ı kerîm tercemesini okumak câiz değildir'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_2",
    "id": 20,
    "question": "Aşağıdaki ifadelerden hangisi yanlıştır ?",
    "options": ['Rükü’da en az üç def’a, (Sübhâne rabbiyel azîm) denir', 'Kirli elbise ile ve iş elbisesi ile namâz kılmak da mekrûhdur', 'Secdede, ayak parmaklarını bükerek uçlarını kıbleye çevirmek sünnetdir', 'Kolları, bacakları, etekleri sığalı, kıvrık, kısa olarak namâz kılmak sünnetdir'],
    "answer_index": 3,
  },


  {
    "questionsId": "nk_3",
    "id": 1,
    "question": "I) Kelime-i şehâdet getirmek \nII) Meleklere inanmak \nIII) Namâz kılmak \nIV) Zekât vermek \nV) Oruc tutmak \nVI) Hacca gitmek \nYukarıdakilerden hangisi İslâmın şartlarındandır ?",
    "options": ['I, III, IV, V, VI', 'I, II, III, IV, VI', 'I, II, III, V, VI', 'I, II, III, VI'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_3",
    "id": 2,
    "question": "“Zirâ meleklerin kimi devamlı ....., kimi ....., kimi ....., kimi ..... bulunur.” cümlesindeki boşluklara sırasıyla hangileri gelmelidir ?",
    "options": ['kıyamda / tefekkür halinde / seyr halinde / rükü’da', 'rükü’da / kıraat halinde / tefekkür halinde / zikr halinde', 'kıyâmda / rükü’da / secdede / teşehhüdde', 'secdede / zikr halinde / kıyâmda / rükü’da'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_3",
    "id": 3,
    "question": "I) Sabahın farzı \nII) Öğlenin farzı \nIII) İkindinin farzı \nIV) Akşamın farzı \nV) Yatsının farzı \nVI) Vitr-i vâcib \nSeferi olan kişi yukarıdaki namazlardan hangilerini 2 rekat kılar ?",
    "options": ['I, II, III, IV, V, VI', 'I, II, III, IV, V', 'I, II, III, V, VI', 'I, II, III, V'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 4,
    "question": "“Farz ve vâcib namâzları, zaruret olmadıkça, hayvan üzerinde kılmak câiz değildir. Ancak, özr ile kılabilir “ Aşağıdakilerden hangisi Yukarıdaki cümlede geçen zaruri “özürler”den biri değildir ?",
    "options": ['Malının, canının, hayvanının tehlikede olması', 'Yırtıcı hayvan veya düşman olması', 'Yerin çamur olması', 'Havanın karanlık olması'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 5,
    "question": "Kaza namazları ile ilgili aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Vaktinde kılınmayan namâzları kazâ etmek lâzımdır', 'Sünnet olan namazı kazâ etmek sünnettir', 'Vâcib olan namazı kazâ etmek vâcibdir', 'Farz olan namazı kazâ etmek farzdır'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_3",
    "id": 6,
    "question": "Aşağıdaki vakitlerden hangisinde nâfile namaz kılmak mekruhtur ?",
    "options": ['Öğlenin farzından sonra', 'İkindinin farzından önce', 'Sabahın farzından sonra', 'Vitr namazından sonra'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_3",
    "id": 7,
    "question": "İmâmın, Cum'a ve Bayram namazları dışındaki her namazda; birinci rekatte, ikinci rekatte okuyacağının iki misli uzun okumasının hükmü nedir ?",
    "options": ['Mekruhtur', 'Haramdır', 'Vaciptir', 'Sünnettir'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 8,
    "question": "Aşağıdaki hallerden hangisinde secde-i sehv yapmak gerekmez ?",
    "options": ['Farzın tehirinde', 'Vacibin tehirinde', 'Vacibin terkinde', 'Birden fazla Sünnetin terkinde'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 9,
    "question": "Aşağıdakilerden hangisi namazın sünnetlerinden değildir ?",
    "options": ['Kıyamda sağ eli, sol elin üstüne koymak', 'İftitah tekbirinden sonra (sübhâneke) okumak', 'Son rekatte otururken (ettehiyyâtü) okumak', 'Selam verirken iki yanına bakmak'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_3",
    "id": 10,
    "question": "Aşağıdakilerden hangisi namazı bozan şeylerden biri değildir ?",
    "options": ['Ağızda kırâete mani olacak bir şey bulundurmak', 'Birinin selâmına başı ile cevâb vermek', 'Özrsüz, öksürmek veyâ boğazını ayıklamak', 'Namâz içinde sadece kendi işiteceği kadar gülmek'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_3",
    "id": 11,
    "question": "Aşağıdakilerden hangisi namâzın vâciblerinden değildir ?",
    "options": ['İkinci rek’atde teşehhütden fazla oturmamak', 'Son rek’atde otururken (Ettehıyyâtü) düâsını okumak.', 'Namâzda ta’dîl-i erkâna riâyet etmek', 'İftitâh tekbîrinden sonra, (Sübhâneke) okumak'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 12,
    "question": "Aşağıdakilerden hangisini nemazda yaptığımızda secde-i sehv yapmamız gerekmez ?",
    "options": ['Sesli okuması îcâb eden yerde, sessiz okumak', 'Son oturuşda (Salevât) düâlarını okumamak', 'Oturması lâzım gelen yerde kalkmak', 'Sessiz okuması gereken yerde, sesli okumak'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_3",
    "id": 13,
    "question": "Aşağıdakilerden hangisi namâzın sünnetlerinden biri değildir ?",
    "options": ['Namâzda gözleri yummak', 'Namâzda elleri kulağa kaldırmak', 'Tekbîr aldıkdan sonra, el bağlamak', 'Selâm verirken iki yanına bakmak'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_3",
    "id": 14,
    "question": "Aşağıdakilerden hangisi namâzın mekruhlardan biri değildir ?",
    "options": ['Ağzını ve burnunu örterek kılmak', 'İkinci rek’atde, birinciden üç âyet uzun okumak', 'Elbiseyi giymeyip, omuzlarına alarak kılmak', 'Secdeye, burnundan sonra alnını koymak'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 15,
    "question": "Aşağıdakilerden hangisi namâz dışında mekrûh olan şeylerden değildir ?",
    "options": ['Güneşe ve aya karşı abdest bozmak', 'Kıbleye karşı özrsüz ayaklarını veyâ bir ayağını uzatmak', 'Yüksekde bulunan din kitabına karşı ayak uzatmak', 'Küçük çocukları kıbleye karşı tutarak abdest bozdurmak'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_3",
    "id": 16,
    "question": "Aşağıdakilerden hangisi namâz bozan durumlardan biri değildir ?",
    "options": ['Namâz içinde gülmek', 'Namâz içinde inlemek ve âh etmek', 'Özrsüz, öksürmek veyâ buğazını ayıklamak', 'Farz kılarken, özrsüz dıvara ve direğe dayanmak'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 17,
    "question": "Aşağıdakilerden hangisi imam olma şartlarından biri değildir ?",
    "options": ['Bülûğ yaşında olmak', 'Akllı olmak', 'Mukim olmak', 'Müslimân olmak'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_3",
    "id": 18,
    "question": "Aşağıdaki ifadelerden hangisi yanlıştır ?",
    "options": ['Mesbûk, imâma birinci rek’atde yetişemiyene denir', 'Müdrik, iftitâh tekbîrine yetişemiyene denir', 'İmâma uyanlar dört çeşitdir', 'Vitr namâzı, Ramezânda cemâ’at ile kılınır'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_3",
    "id": 19,
    "question": "Aşağıdaki ifadelerden hangisi yanlıştır ?",
    "options": ['İmâm kunût okumazsa cemâ’at de okumaz', 'İmâm ikiden çok secde yaparsa, cemâ’at yapmaz', 'İmâm beşinci rek’ate kalkarsa, cemâ’at kalkmaz', 'İmâm cenâze namâzında, dörtden çok tekbîr yaparsa cemâ’at yapar'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_3",
    "id": 20,
    "question": "Aşağıdaki ifadelerden hangisi doğrudur ?",
    "options": ['Sübhâneke okumak, Cenâze Namâzının farzıdır', 'Salevât okumak, Cenâze Namâzının farzıdır', 'Dört kerre tekbîr getirmek Cenâze Namâzının farzıdır', 'Kadınlara Cum’a namâzı farzdır'],
    "answer_index": 2,
  },

  {
    "questionsId": "nk_4",
    "id": 1,
    "question": "Arapçada namaza ne denir ? ( Namaz Farsçadır)",
    "options": ['İkâme', 'Edâ', 'Salât', 'Tahiyyât'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_4",
    "id": 2,
    "question": "Aşağıdakilerden hangisi vâcib namazlardan değildir ?",
    "options": ['Bayram namazı', 'Adak olarak adanmış namaz', 'Vitr namazı', 'Cuma namazı'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_4",
    "id": 3,
    "question": "Müekked sünnet ne demektir ?",
    "options": ['Peygamberimizin nâdiren yaptığı ibâdetler', 'Peygamberimizin kuvvetle emrettiği ibâdetler', 'Peygamberimizin güzel ahlakı', 'Sünnet olup olmadığı şüpheli ibâdetler'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_4",
    "id": 4,
    "question": "Namaza başlarken “Allahü ekber” demenin hükmü nedir ?",
    "options": ['Farz', 'Vâcib', 'Müekked Sünnet', 'Müstehab'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_4",
    "id": 5,
    "question": "Aşağıdakilerden hangisi abdestin farzlarından değildir ?",
    "options": ['Yüzü bir kere yıkamak', 'Niyet etmek', 'İki ayağı birer kere yıkamak', 'Başın dörtde bir kısmını mesh etmek'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_4",
    "id": 6,
    "question": "Peygamberimizin abdestten sonra 3 defa okunması halinde peygamberler ile haşr olmaya vesîle olacağını söylediği sure hangisidir ?",
    "options": ['İhlâs suresi', 'Fâtiha suresi', 'Kadir Suresi', 'Duhâ suresi'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_4",
    "id": 7,
    "question": "Aşağıdakilerden hangisi abdestin sünnetlerinden değildir ?",
    "options": ['Yıkanacak yerleri üç kere yıkamak', 'İki kulağı mesh etmek', 'Abdeste başlarken besmele okumak', 'Yüzü yıkarken, göz pınarını, çapakları temizlemek'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_4",
    "id": 8,
    "question": "Aşağıdakilerden hangisi hanefi mezhebinde abdesti bozmaz ?",
    "options": ['Namazda uyumak', 'Sülük çok kan emerse', 'Tükürdüğünde, kan tükürükten çok olması', 'Namazda yanındaki işitecek kadar sesli gülmek'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_4",
    "id": 9,
    "question": "Cünüb kimse aşağıdakilerden hangisini yapabilir ?",
    "options": ['Kur’ân-ı kerîmi tutmak', 'Tilâvet secdesi yapmak', 'Başkasıyla müsâfaha etmek', 'Mescide girmek'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_4",
    "id": 10,
    "question": "Aşağıdakilerden hangisi hanefî mezhebinde gusül abdestinin sünnetlerinden değildir ?",
    "options": ['Bütün bedeni, üç defa oğarak yıkamak', 'Önce elleri yıkamak', 'Guslü bitirdikten sonra namaz abdesti almak', 'Niyet etmek'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_4",
    "id": 11,
    "question": "Aşağıdakilerden hangi üçünde de verilenle teyemmüm sahihtir ?",
    "options": ['Taş, Kum, Tahta', 'Taş, Kireç, Tahta', 'Toprak, Demir, Kum', 'Kum, Toprak, Kireç'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_4",
    "id": 12,
    "question": "Aşağıdakilerden hangisinde bulunanların hepsi, bir erkeğe mahremdir ?",
    "options": ['Hala, Süt Teyze, Yenge', 'Teyze, Kaynana, Amca kızı', 'Süt kız kardeşin kızı, Gelin, Hala', 'Teyze kızı, Yenge, baldız'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_4",
    "id": 13,
    "question": "“Hanefi mezhebinde olan bir kimse, ..... günden az kalmak niyeti ile ..... kilometre ve daha uzak bir yere giderse misafir olur.” cümlesindeki boşluklara sırayla hangileri gelmelidir ?",
    "options": ['dört / seksen', 'on beş / yüz dört', 'dört / doksan altı', 'dört / yüz dört'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_4",
    "id": 14,
    "question": "“Nafile namazları ayakta kılmaya gücü yeterken, oturarak kılmak, ….. . Yolda, yani şehir, köy haricinde, nafile namazları hayvan üzerinde kılmak ….. .” cümlesindeki boşluklara sırayla hangileri gelmelidir ?",
    "options": ['her zaman ve her yerde caizdir / caizdir', 'hiç caiz değildir / caiz değildir', 'hiç caiz değildir / caizdir', 'zaruret durumunda caizdir / caizdir'],
    "answer_index": 0,
  },
  {
    "questionsId": "nk_4",
    "id": 15,
    "question": "Giden gemide olan biri farz namazını nasıl kılar ?",
    "options": ['Gemide namaz kılınmadığı için inince kılar', 'Kıbleye karşı namaza durur, gemi döndükçe o da kıbleye döner', 'Namazı istediği cihete doğru kılar', 'Namaza kıbleye karşı başlar, gemi dönerse zararı olmaz'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_4",
    "id": 16,
    "question": "Kaza namazları ile ilgili aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Farz borcu olanın sünnetleri kabul olmaz', 'Akşamın sünneti yerine akşamın kazasını kılarken 2 rekat kılınır', 'Sünnet yerine kaza kılmakla, sünnet de yerine getirilmiş olur', 'Teravih namazı kılarken, kazaya niyet edilebilir'],
    "answer_index": 1,
  },
  {
    "questionsId": "nk_4",
    "id": 17,
    "question": "Aşağıdaki vakitlerden hangisinde nâfile namaz kılmak mekruhtur ?",
    "options": ['Öğlenin farzından sonra', 'İkindinin farzından önce', 'Güneş tam tepedeyken', 'Vitr namazından sonra'],
    "answer_index": 2,
  },
  {
    "questionsId": "nk_4",
    "id": 18,
    "question": "İmâmın, Cum'a ve Bayram namazları dışındaki her namazda; birinci rekatte, ikinci rekatte okuyacağının iki misli uzun okumasının hükmü nedir ?",
    "options": ['Mekruhtur', 'Haramdır', 'Vaciptir', 'Sünnettir'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_4",
    "id": 19,
    "question": "Aşağıdakilerden hangisi namazı bozan şeylerden biri değildir ?",
    "options": ['Ağızda kırâete mani olacak bir şey bulundurmak', 'Özrsüz, öksürmek veyâ boğazını ayıklamak', 'Namâz içinde sadece kendi işiteceği kadar gülmek', 'Bir rüknde iki defa eliyle yüzünü kaşımak'],
    "answer_index": 3,
  },
  {
    "questionsId": "nk_4",
    "id": 20,
    "question": "İslâmın beş şartı üstünlük sırasına göre hangi seçenekte doğru verilmiştir ?",
    "options": ['Kelime-i Şehâdet, Namâz, Oruc, Hac, Zekât', 'Namâz, Kelime-i Şehâdet, Oruc, Hac, Zekât', 'Oruc, Kelime-i Şehâdet, Namâz, Hac, Zekât', 'Hac, Kelime-i Şehâdet, Zekât, Namâz, Oruc'],
    "answer_index": 0,
  },



  {
    "questionsId": "ia_1",
    "id": 1,
    "question": "Mızraklı İlmihâlinin asıl ismi nedir ?",
    "options": ['Nîmet-i İslam', 'Miftâhü’l- Cennet', 'Nûru’l- Îzah', 'Eyyühe’l- Veled'],
    "answer_index": 1,
  },
  {
    "questionsId": "ia_1",
    "id": 2,
    "question": "“(Miftâh-ul Cennet) ilm-i hâlinin yazarı sâlih bir zat imiş. Okuyanlara faydalı olur.” buyuran Derin İslâm âlimi kimdir ?",
    "options": ['Seyyid Abdülhakîm Arvâsî', 'Seyyid Fehîm Ârvâsî', 'Seyyid Tâhâ-i Hakkârî', 'Seyyid Abdülkâdir-i Geylânî'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_1",
    "id": 3,
    "question": "Yetmişiki bozuk fırkanın en zararlısı aşağıdakilerden hangisidir ?",
    "options": ['İsmâ\'îliyye', 'Mutezile', 'Hariciyye', 'Cebriyye'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_1",
    "id": 4,
    "question": "İman ve amel ile alakalı aşağıdaki bilgilerden hangisi yanlıştır ?",
    "options": ['İslamiyyet ahkamı amele mütealliktir, İmana müteallik değildir', 'Amelsiz iman makbüldür amma imansız amel makbul değildir', 'İman da amel de vasiyyet edilmez', 'İman farz-ı daimdir. Amel vakti gelince farz olur'],
    "answer_index": 2,
  },
  {
    "questionsId": "ia_1",
    "id": 5,
    "question": "“Kelime-i tevhîdin sekiz ismi vardır.” Aşağıdakilerden hangisi bunlardan değildir ?",
    "options": ['Kelime-i tayyibe ', 'Dâvet-ül-Hak', 'Urvet-ül-vüska', 'Kelime-i Vera'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_1",
    "id": 6,
    "question": "Peygamber Efendimiz aleyhisselam ile ilgili aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Efendimiz aleyhisselamın 11 hatunu vardı', 'Oğlu İbrahim hazret-i Mariye’den olmuştur', 'Cümle kızları içinde efdali hazret-i Fâtımadır', 'Cümle evlatları kendinden evvel vefat eylemiştir'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_1",
    "id": 7,
    "question": "Aşağıdakilerden hangisi İmam-ı A’zam hazretlerinin hocalarından değildir ?",
    "options": ['Hammad', 'İbrahim Nehâi', 'Alkama bin Kays', 'Abdullah ibni Abbas'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_1",
    "id": 8,
    "question": "Hadis-i şerifte bildirilen günahlar arasında cezası en çabuk verilecek olan günah hangisidir ?",
    "options": ['Hükümete isyan', 'Ana babaya asi olmak', 'Kul hakkı', 'Hırsızlık'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_1",
    "id": 9,
    "question": "Pakistan’da Camia-i Habibiyye dekanı olan, hacca gittiğinde vehhabi imamın hoparlör ile namaz kıldırdığını görüp namazlarını ayrı kıldığı için ellerine kelepçe takılarak hapsedilen zat kimdir ?",
    "options": ['Muhammed Madras', 'Yunus zade Ahmed Vehbi', 'İmam Hinduvani', 'Habib-ür Rahman'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_1",
    "id": 10,
    "question": "Guslün farzları hakkında aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Hanefi mezhebinde farzı 3 tür', 'Maliki mezhebinde farzı 7 dir', 'Şafii mezhebinde 2 dir', 'Hanbeli mezhebinde 1 dir'],
    "answer_index": 1,
  },
  {
    "questionsId": "ia_1",
    "id": 11,
    "question": "Abdestin farzları hakkında aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Hanefi mezhebinde farzı 4 tür', 'Şafii mezhebinde 5 tir', 'Maliki mezhebinde farzı 7 dir', 'Hanbeli mezhebinde 6 dır'],
    "answer_index": 1,
  },
  {
    "questionsId": "ia_1",
    "id": 12,
    "question": "Sular hakkında aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Sular dört nevdir: mutlak, mukayyed, meşkük, müsta’mel', 'Ma-i mukayyed ile abdest ve gusl caizdir', 'Ma-i meşkük himarın ve anası himar olan katırın içtiği suyun artığıdır', 'Ma-i meşkük ile abdest ve gusül caizdir'],
    "answer_index": 1,
  },
  {
    "questionsId": "ia_1",
    "id": 13,
    "question": "I. Ma-i müsta’mel bedenden ayrılan mıdır yere düşen midir bu ihtilaflıdır\nII. İmam-ı Azam’a göre necaset-i galizadı\nIII. İmam-ı Muhammed’e göre necaset-i hafifedir\nIV. İmam-ı Ebu Yusuf’a göre paktır\nMa-i musta’mel hakkında hangileri doğrudur ?",
    "options": ['I ve II', 'I, II ve III', 'I, II ve IV', 'Hepsi'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_1",
    "id": 14,
    "question": "Kağıt paraların kıymeti kıymet-i itibariyyedir. İtibardan düşünce kıymeti kalmaz. Bu sebepten fitra ve zekatı kağıt para ile vermek caiz olmaz buyuran İslam alimi kimdir ?",
    "options": ['Ahmed Tahtavi', 'İmam-ı Rabbani', 'Abdülgani Nablüsi', 'Seyyid Abdülhakim Arvasi'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_1",
    "id": 15,
    "question": "Altının nisabı kaç miskaldir ?",
    "options": ['10', '20', '40', '60'],
    "answer_index": 1,
  },



  {
    "questionsId": "ia_2",
    "id": 1,
    "question": "I. Zevcesine\nII. Kölesine\nIII. Dedesine\nIV. Kayın Validesine\nV. Kardeşine\nYukarıdakilerden hangilerine zekat verilmez ?",
    "options": ['I ve II', 'I, II, III', 'III ve IV', 'III ve V'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_2",
    "id": 2,
    "question": "Hanefi mezhebinde tadil-i erkan farzdır buyuran alim/alimler kimdir/kimlerdir ?",
    "options": ['İmam-ı Azam', 'İmam-ı Ebû Yusuf', 'İmam-ı Muhammed', 'Tarafeyn'],
    "answer_index": 1,
  },
  {
    "questionsId": "ia_2",
    "id": 3,
    "question": "İlk minareyi kim yaptırmıştır ?",
    "options": ['Ömer bin Abdilaziz', 'Harun Reşid', 'Hazret-i Muaviye', 'Hazret-i Ömer'],
    "answer_index": 2,
  },
  {
    "questionsId": "ia_2",
    "id": 4,
    "question": "I. Kur’ân-ı kerim okuyanın\nII. Din bilgisi öğrenmekte ve öğretmekte olanın\nIII. Cenaze namazı kılanın\nIV. Yemekte olanın\nYukarıdakilerden hangisi ya da hangileri için sünnete uygun ezanı tekrar etmek lazım değildir ?",
    "options": ['I ve II', 'II ve III', 'I, II ve IV', 'II, III ve IV'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_2",
    "id": 5,
    "question": "Ezân-ı Muhammedi hakkında aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Ezan mescidin içinde okunmaz', 'Arabiden başka dil ile ezan okunmaz', 'Müezzinin sesini takatinden fazla yükseltmesi haramdır', 'Birkaç müezzinin bir ezanı birlikte okumaları (ezân-ı cavk) caizdir'],
    "answer_index": 2,
  },
  {
    "questionsId": "ia_2",
    "id": 6,
    "question": "I. Yemekten sonra\nII. Namazdan sonra\nIII. Tavafta\nIV. Yatarken\nResulullah efendimiz yukarıdaki dualarının hangisi yada hangilerinde kollarını ileri uzatmaz ve ellerini yüzüne sürmezdi ?",
    "options": ['Yalnız I', 'I ve III', 'III ve IV', 'I, III ve IV'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_2",
    "id": 7,
    "question": "Aşağıdakilerden hangisi namazı bozanlardan değildir ?",
    "options": ['Kıyamda okuduğu rükuda tamamlamak', 'İhtiyarsız farzın birini terk etmek', 'Saçını sakalını taramak', 'Kendi imamından gayrıya feth etmek'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_2",
    "id": 8,
    "question": "Efendimiz aleyhisselam gemide namaz kılmayı kime talim buyurmuştur ?",
    "options": ['Sad bin Ebi Vakkas', 'Hazret-i Ali', 'Ebû Ubeyde bin Cerrah', 'Cafer-i Tayyar'],
    "answer_index": 3,
  },
  {
    "questionsId": "ia_2",
    "id": 9,
    "question": "Fukara-i sabirin ağniya-i şakirinden kaç yıl evvel cennete girse gerektir ?",
    "options": ['500 yıl', '550 yıl', '700 yıl', '1000 yıl'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_2",
    "id": 10,
    "question": "Aşağıdakilerden hangisi 8 cennetten birisi değildir ?",
    "options": ['Dâr-ı cemal', 'Dâr-ı karar', 'Dâr-ı selam', 'Cennet-ül-huld'],
    "answer_index": 0,
  },
  {
    "questionsId": "ia_2",
    "id": 11,
    "question": "Ahiretin bir günü dünyanın kaç senesine denk gelmektedir ?",
    "options": ['100 sene', '500 sene', '1.000 sene', '10.000 sene'],
    "answer_index": 2,
  },
  {
    "questionsId": "ia_2",
    "id": 12,
    "question": "Bir yıllık namaz ıskatının değeri kaç altındır ?",
    "options": ['7', '15', '60', '70'],
    "answer_index": 2,
  },
  {
    "questionsId": "ia_2",
    "id": 13,
    "question": "Tarafeyne göre Cuma namazı için imam efendiden gayrı kaç âdem bulunmalıdır ?",
    "options": ['2', '3', '4', '5'],
    "answer_index": 1,
  },
  {
    "questionsId": "ia_2",
    "id": 14,
    "question": "Bu ümmetten ilk terk olunan sünnet nedir ?",
    "options": ['Misvak kullanmak', 'Tebkir (Cuma namazına erken gitme)', 'Rayiha-i tayyibe', 'Sıla-i rahm'],
    "answer_index": 1,
  },
  {
    "questionsId": "ia_2",
    "id": 15,
    "question": "Aşağıdakilerden hangisi cemaate gitmemek için özür değildir ?",
    "options": ['Nadir bulunan tefsir dersini kaçırmamak', 'Havanın çok karanlık olması', 'Sevdiği yemeği kaçırmak korkusu', 'Çamur'],
    "answer_index": 0,
  },


  {
    "questionsId": "hloi_1",
    "id": 1,
    "question": "İ’tikâdnâme kitabının müellifi kimdir ?",
    "options": ['İbni Âbidîn', 'İmâm Rabbanî', 'Mevlânâ Hâlid-i Bağdâdî', 'M. Hadimi'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_1",
    "id": 2,
    "question": "Aşağıdaki eşleştirmelerden hangisi yanlıştır ?",
    "options": ['Necdî-Vehhabî', 'Sünnî-Ehli Sünnet', 'Şi’i-Fırka-i Mel’une', 'Sünnî-Fırka-i Naciyye'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_1",
    "id": 3,
    "question": "Fırka-i Mel’une’nin kelime manası nedir ?",
    "options": ['Yanlış fırka', 'Lanetlenmiş fırka', 'Bidat fırkası', 'Cehennemlik fırka'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 4,
    "question": "Vehhabilere niçin fırka-i mel’une denir ?",
    "options": ['Müslümanlara kafir dedikleri için', 'Allahü teala göktedir dedikleri için', 'Kabir ziyaretine karşı oldukları için', 'Türbeleri yıktıkları için'],
    "answer_index": 0,
  },
  {
    "questionsId": "hloi_1",
    "id": 5,
    "question": "Kalb ile i’tikâd edilmesi, ya’nî inanılması lâzım olan bilgilerin ilmine ne denir ?",
    "options": ['Fıkıh', 'Tasavvuf', 'Usûl-i din', 'Ahkâm-ı İslâmiyye'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_1",
    "id": 6,
    "question": "Beden ile veyâ kalb ile yapılacak ve sakınılacak ibâdet bilgilerinin ilmine ne denir ?",
    "options": ['Kelam', 'Fürû-i din', 'Akaid', 'Usûl-i fıkh'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 7,
    "question": "Muhammed aleyhisselâmın sözlerine (Hadîs-i şerîf) denir. Bunlardan, ma’nâsı Allahü teâlâ tarafından, kelimeleri Muhammed aleyhisselâm tarafından olan hadîs-i şerîflere ..... denir. Hadîs kitâbları çokdur. Bunlardan,  ..... kitâbları meşhûrdur.\n\n"
        "Yukardaki boşluklara ne gelecektir ?",
    "options": ['Mütevatir Hadîs - Hadîka ve Berîka', 'Vahiy - Mektûbat ve Mesnevi', 'Hadîs-i kudsî - Buhârî ve Müslim', 'Sahih Hadîs - Tirmizi ve Ebu Davud'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_1",
    "id": 8,
    "question": "Allahü teâlânın emrlerinden, inanılacak bilgilere ....., yapılacak olanlara (Farz), sakınılacak olanlara (Harâm) denir. Farzlara ve harâmlara ..... denir. İslâm bilgilerinden birine bile inanmıyana (Kâfir) denir.\n\n"
        "Yukardaki boşluklara ne gelecektir ?",
    "options": ['İ’tikâd - akaid', 'Tasavvuf - fıkıh', 'Akaid - i’tikâd', 'Îmân - Ahkâm-ı islâmiyye'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_1",
    "id": 9,
    "question": "Cebrâîl aleyhisselâm her sene bir kerre gelip, o âna kadar inmiş olan Kur’ân-ı kerîmi, ..... okur, Peygamberimiz de tekrâr ederdi. Âhırete teşrîf edeceği sene, iki kerre gelip, temâmını okudular.\n\n"
        "Yukardaki boşluğa ne gelecektir ?",
    "options": ['Ka’be’de', 'Levh-il mahfûzdaki sırasına göre', 'Esbab-ı nüzûlüyle birlikte', 'Tecvid ile'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 10,
    "question": "Peygamber efendimiz hicretten kaç sene sonra vefat ettiler ?",
    "options": ['7', '9', '10', '12'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_1",
    "id": 11,
    "question": "Kâfirler, ..... ve ..... olmak üzere ikiye ayrılır.\n\n"
        "Yukardaki boşluklara ne gelecektir ?",
    "options": ['Hrıstiyan - yahudi', 'Zararlı - zararsız', 'Mürted - zındık', 'Kitaplı - kitapsız'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_1",
    "id": 12,
    "question": "Allahü teâlâdan başka olan herşeye ne denir ?",
    "options": ['Mevcut', 'Vâcib', 'Mâsivâ', 'Haram'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_1",
    "id": 13,
    "question": "(Mümkin-ül-vücûd) için hangisi doğrudur ?",
    "options": ['Varlığı lazımdır', 'Var da olabilir, yok da olabilir', 'Var olamaz. Hep yok olması lâzımdır', 'Hiç var olmamıştır'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 14,
    "question": "(Vâcib-ül-vücûd) için aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Hep vardır', 'Önceleri ve sonsuz sonraları hiç yok olamaz', 'Yalnız Allahü teâlâ vâcib-ül-vücûddür', 'Şerîk-i bârî böyledir'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_1",
    "id": 15,
    "question": "Var olamaz. Hep yok olması lâzımdır. Şerîk-i bârî böyledir. Ya’nî, Allahü teâlâya ortak, Allahü teâlâ gibi ikinci bir tanrı var olamaz.\n\n"
        "Yukarda anlatılan kavram nedir ?",
    "options": ['Vâcib-ül-vücûd', 'Mümteni’-ul-vücûd', 'Mümkin-ül-vücûd', 'Adem'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 16,
    "question": "Hangi sıfatın manası yanlıştır ?",
    "options": ['(Hay) diri', '(Mürîd) hizmet edici', '(Basîr) görücü', '(Mütekellim) söyleyici'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 17,
    "question": "(Gözün yapısındaki nizâmı, incelikleri düşündükçe, hayretden tepem atacak gibi oluyor) diyen bilim adamı kimdir ?",
    "options": ['Lavoisier', 'Darwin', 'Dalton', 'Meyer Leksikon'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 18,
    "question": "İmam ve İslam kitabında anlatılan uzun hadîs-i şerifi hangi sahabi rivayet etmiştir ?",
    "options": ['Ebu Hureyre “radiyallahü anh”', 'Hazreti Ebu Bekir “radiyallahü anh”', 'Hazreti Ömer “radiyallahü anh”', 'Hazreti Ali “radiyallahü anh”'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_1",
    "id": 19,
    "question": "Cibril hadisinde geçen Cebrail aleyhisselamın dizlerini, peygamberimizin mübârek dizlerine yanaşdırmasının sebebi nedir ?",
    "options": ['Peygamber efendimizi çok sevdiği için', 'Başka yer olmadığı için', 'Sesini rahat duyabilmek için', 'Din bilgisi öğrenmek için utanmak doğru olmadığını göstermek için'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_1",
    "id": 20,
    "question": "Meşhur Cibril hadisinde Cebrail aleyhisselamın ilk suali nedir ?",
    "options": ['Îmânın ne olduğunu bana bildir', 'yâ Resûlallah! Bana islâmiyyeti, müslimânlığı anlat', 'İhsanın ne olduğunu bana bildir', 'Kıyamet ne zaman kopacak ?'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 21,
    "question": "Hicretin olduğu senenin muharrem ayının birinci günü hangi takvimin sene başı kabul edildi ?",
    "options": ['Hicrî-şemsî', 'Hicrî-kamerî', 'Hicrî-rûmî', 'Miladî-şemsî'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 22,
    "question": "Aşağıdakilerden hangisi İslamiyetin beş şartından biri değildir ?",
    "options": ['Zekat vermek', 'Kurban kesmek', 'Oruç tutmak', 'Hacca gitmek'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_1",
    "id": 23,
    "question": "Hazreti Amine’nin babasının adı nedir ?",
    "options": ['İbrahim', 'Kureyş', 'Amr', 'Veheb'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_1",
    "id": 24,
    "question": "Peygamberimize peygamberliği kaç yaşında iken bildirildi ?",
    "options": ['25', '30', '33', '40'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_1",
    "id": 25,
    "question": "(Bi’set senesi) hangi seneye denir ?",
    "options": ['Dünyaya geldiği', 'Peygamberliğin bildirildiği', 'Hicretin olduğu', 'Mekke’nin fethedildiği'],
    "answer_index": 1,
  },

  {
    "questionsId": "hloi_2",
    "id": 1,
    "question": "Peygamber efendimiz hicretten kaç sene sonra vefat ettiler ?",
    "options": ['7', '9', '10', '12'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_2",
    "id": 2,
    "question": "Hicretin olduğu senenin muharrem ayının birinci günü hangi takvimin sene başı kabul edildi ?",
    "options": ['Hicrî-şemsî', 'Hicrî-kamerî', 'Hicrî-rûmî', 'Miladî-şemsî'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_2",
    "id": 3,
    "question": "Toprak mahsulleri zekatına ne isim verilir ?",
    "options": ['Nisab', 'Âşir', 'Fitre', 'Uşr'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_2",
    "id": 4,
    "question": "Zekat kaç sınıf insana verilir ?",
    "options": ['4', '5', '6', '7'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_2",
    "id": 5,
    "question": "Aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Dört türlü zekat malı vardır', 'Bütün zekat malları nisâb mikdârı oldukdan bir sene sonra verilir', 'Zekâtın lügat ma’nâsı, temizlik ve övmek ve iyi, güzel hâle gelmek demekdir', 'Zekât, yedi sınıf insana verilir'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_2",
    "id": 6,
    "question": "Oruçla alakalı aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Ramazana takvîmle önceden hesâb etmekle başlanır', 'Oruç tutmağa (Savm) denir.', 'Savm, lügatde, birşeyi birşeyden korumak demekdir', 'Sâim, oruç tutan kişiye denir'],
    "answer_index": 0,
  },
  {
    "questionsId": "hloi_2",
    "id": 7,
    "question": "Beş vakit namaz ne zaman farz oldu ?",
    "options": ['Kadir gecesi', 'Mirac gecesi', 'Berat gecesi', 'Regaib gecesi'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_2",
    "id": 8,
    "question": "Hicretin 2. senesi hangi ibadetler farz olmuştur ?",
    "options": ['Hac ve Zekat', 'Oruç ve Hac', 'Oruç ve Zekat', 'Namaz ve Oruç'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_2",
    "id": 9,
    "question": "Hac ibadeti hicretin kaçıncı senesinde farz olmuştur ?",
    "options": ['7', '8', '9', '10'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_2",
    "id": 10,
    "question": "Erkeklerin diz ile kasıkları arası hangi mezhepte avret değildir ?",
    "options": ['Hanbeli', 'Şafii', 'Maliki', 'Hanefi'],
    "answer_index": 0,
  },
  {
    "questionsId": "hloi_2",
    "id": 11,
    "question": "Müslimân olan, ya’nî ..... olup, ibâdet eden, fekat, i’tikâdı (Ehl-i sünnet) i’tikâdına uymıyan ve tevbe etmeden ölen kimseye, Cehennemde azâb edecek ise de, böyle ..... müslimânlar, Cehennemde sonsuz kalmıyacakdır\n\nYukardaki boşluklara ne gelecektir ?",
    "options": ['Salih - Muhlis', 'Sünnî - Zındık', 'Ehli Necat - Mezhepsiz', 'Ehli Kıble - Bid’at sahibi'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_2",
    "id": 12,
    "question": "El, ayak, cihet, yer ve bunlar gibi, Allahü teâlâ için câiz olmıyan kelimelerin, âyet-i kerîmelerde ve hadîs-i şerîflerde bulunması, bizim anladığımız ve bildiğimiz, bugün kullanılan ma’nâlarda değildir. Böyle âyet-i kerîmelere ve hadîs-i şerîflere ..... denir\n\nYukardaki boşluğa ne gelecektir ?",
    "options": ['Te’vil', 'Muhkemat', 'Müteşabihat', 'İ’caz'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_2",
    "id": 13,
    "question": "Allahü teâlânın (Sıfât-ı zâtiyye)si kaçtır ?",
    "options": ['5', '6', '7', '8'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_2",
    "id": 14,
    "question": "Allahü teâlânın (Sıfât-ı sübûtiyye)si, (Mâtürîdiyye) mezhebinde  ..... (Eş’ariyye) mezhebinde ise ..... Bu sıfatları da, zâtı gibi, ezelîdir, ebedîdir. Ya’nî sonsuz olarak vardırlar. Mukaddesdirler.\n\nYukardaki boşluklara ne gelecektir ?",
    "options": ['8’dir, 5’dir', '5’dir, 6’dır', '5’dir, 5’dir', '8’dir, 7’dir'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_2",
    "id": 15,
    "question": "Eş’ariyye mezhebinde, ..... sıfatı, kudret sıfatı ile birdir.\n\nYukardaki boşluğa ne gelecektir ?",
    "options": ['Hayat', 'İrade', 'Tekvin', 'Vahdaniyyet'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_2",
    "id": 16,
    "question": "Aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Allahü teâlânın ismleri (Tevkîfî)dir', 'Allahü teâlânın ismleri sonsuzdur', 'Başka dillerdeki Dieu, Gott ve God kelimeleri de, ilah, ma’bûd ma’nâsına kullanılabilir', 'Allahü teâlânın sekiz sıfât-ı sübûtiyyesi, zâtının aynıdır'],
    "answer_index": 3,
  },
  {
    "questionsId": "hloi_2",
    "id": 17,
    "question": "Melekler için aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Sayısı en çok olan mahlûk meleklerdir', 'Cisimdir. Latîfdir. Gaz hâlinden de dahâ latîfdirler', 'Cehennem meleklerinin büyüğüne (Rıdvân) denir', 'Cehennem zebânîlerinin büyükleri ondokuzdur'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_2",
    "id": 18,
    "question": "Huzur-ı ilahide bulunan meleklere ne denir ?",
    "options": ['Kerûbiyân', 'Mukarrebîn', 'Rûhâniyân', 'Mübeşşir'],
    "answer_index": 1,
  },
  {
    "questionsId": "hloi_2",
    "id": 19,
    "question": "Semâvî kitâblardan bize bildirileni yüz dörtdür. Bunlardan ..... suhuf (Âdem) aleyhisselâma, ..... suhuf Şis (Şît) aleyhisselâma, ..... suhuf (İdrîs) aleyhisselâma, ..... suhuf (İbrâhîm) aleyhisselâma indirildiği meşhûrdur.\n\nYukardaki boşluklara ne gelecektir ?",
    "options": ['10-30-50-10', '10-25-50-20', '10-50-30-10', '20-30-50-20'],
    "answer_index": 2,
  },
  {
    "questionsId": "hloi_2",
    "id": 20,
    "question": "(Tevrât) kitâbı ..... aleyhisselâma, (Zebûr) kitâbı ..... aleyhisselâma, (İncîl) kitâbı Îsâ aleyhisselâma ve (Kur’ân-ı kerîm) Muhammed aleyhisselâma indirilmişdir.\n\nYukardaki boşluklara ne gelecektir ?",
    "options": ['Musa - Davud', 'Musa - Üzeyr', 'Musa - Harun', 'Musa - Yahya'],
    "answer_index": 0,
  },
];
const List survival_questions = [ //map list, Questions and answers stored locally
  {
    "questionsId": "surv_1",
    "id": 1,
    "question": "İmâm-ı Rabbani hazretlerinin ve mahdumları Muhammed Masum hazretlerinin mektublarının bir araya getirilmesiyle oluşturulan mektubât eserleri sırasıyla kaçar cilttir ?",
    "options": ['6 / 6', '3 / 1', '4 / 4', '3 / 3'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 2,
    "question": "(Miftâh-ı genc-i kadîm)in kelime manası nedir ?",
    "options": ['Yaratılmışların en üstünü', 'Eshâb-ı Kirâm’ın güzel ahlakı', 'Geçmiş senelerdeki namaz borcunun miktarı', 'Sonsuz hazinenin anahtarı'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 3,
    "question": "’Fırka-i mel’ûne’ de denilen bozuk fırka hangisidir ?",
    "options": ['Şî’î', 'Vehhabi', 'Mutezile', 'Müşebbihe'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 4,
    "question": "Uşr ne zaman verilir ?",
    "options": ['Mahsulün satıldığı gün', 'Mahsul alınır alınmaz', 'Mahsul alındıktan 1 hicri sene sonra', 'Mahsul bozulmadığı müddetçe istediği zeman'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 5,
    "question": "Peygamber Efendimizin annesi, Hazreti Amine’nin babasının ismi nedir ?",
    "options": ['Sâd', 'Huzeyfe', 'Abdülmuttalib', 'Veheb'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 6,
    "question": "Aşağıdakilerden hangisi 54 farzdan birisi değildir ?",
    "options": ['Kanâ’at etmek', 'Zalim hükümete isyan etmek', 'Babaya ve anaya iyilik etmek', 'Yok yere yemîn etmemek'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 7,
    "question": "“İslâmiyyet, kalb ile inanılacak ..... bilgileri ve beden ile yapılacak ..... bilgileridir. Îman ve ahkâm ilmleri ..... kitaplarından öğrenilir.” cümlesindeki boşluklara sırayla hangileri gelmelidir ?",
    "options": ['ahkâm / îmân / kelam', 'fıkh / ahkâm / felsefecilerin', 'îmân / ahkâm-ı islâmiyye / ehl-i sünnet âlimlerinin', 'din / şer’î / menkıbe'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 8,
    "question": "“Kadınların yalnız başlarına cemâat ile namaz kılmaları …………. “ boşluğa gelmesi gereken ifade hangisidir ?",
    "options": ['Müfsiddir', 'Mekruhtur', 'Ruhsattır', 'Zarurettir'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 9,
    "question": "Regâib, Berât ve Kadr namazlarını cemâat ile kılmanın hükmü nedir ?",
    "options": ['Vacip', 'Farz', 'Müstehab', 'Mekrûh'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 10,
    "question": "Aşağıdakilerden hangisini imâm yapmazsa, cemaat de yapmaz ?",
    "options": ['Dört rekatli namazın ikinci rekatinde oturmak', 'İftitah tekbirinde elleri kaldırmak', 'Rükûya eğilirken tekbir getirmek', 'Sübhâneke okumak'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 11,
    "question": "Aşağıdakilerden hangisi cenâze namazının farzlarındandır ?",
    "options": ['Salevât okumak', 'Kunut duâsı okumak', 'Dört kere tekbir getirmek', 'Meyyit için istiğfâr okumak'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 12,
    "question": "Müslimânlığın başlangıcında ilk olarak farz olan ibadet hangisidir ?",
    "options": ['Beş vakt namâz', 'Kelime-i şehâdet', 'Zekât', 'Hac'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 13,
    "question": "Abdest alırken [ Allahümme sebbit kademeyye ales-sırâtı yevme tezillü fîhilekdâmü ] düâsı ne zaman okunur ?",
    "options": ['Sol kolu üç def’a yıkarken', 'Sağ kolu üç def’a yıkarken', 'Sol ayağı üç def’a yıkarken', 'Sağ ayağı üç def’a yıkarken'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 14,
    "question": "Özr ile kaçırıp, kazaya kalmış namazları bulunan bir kimsenin, bunları ima ile de kılmaya gücü yeter iken kılmamış ise, öleceği zaman, keffaretinin iskat edilmesi için vasıyyet etmesinin hükmü nedir ?",
    "options": ['Müstehab', 'Sünnet-i Müekkede', 'Vâcib', 'Farz'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 15,
    "question": "Aşağıdakilerden hangisi 54 farzdan birisi değildir ?",
    "options": ['Şirk koşmamak', 'Kibirli olmaktan sakınmak', 'Kanâ’at etmemek', 'Abdest almak'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 16,
    "question": "Aşağıdakilerden hangisi Peygamberlerde “aleyhimüsselâm” bulunan yedi sıfatdan birisi değildir ?",
    "options": ['İsmet', 'Teblig', 'Adalet', 'Metanet'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 17,
    "question": "Adem, İdris, Şit ve İbrahim (aleyhimüsselam)a sırasıyla kaçar suhûf gönderilmiştir ?",
    "options": ['10 / 30 / 50 / 10', '10 / 30 / 50 / 1', '5 / 10 / 30 / 50', '10 / 50 / 30 / 10'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 18,
    "question": "Azâb meleklerinin büyüklerine, Huzûr-i ilâhîde bulunan meleklere ve rahmet meleklerine sırasıyla ne denir ?",
    "options": ['Kerûbiyân, Mâlik, Mukarrebîn', 'Rûhânîyân, Mukarrebîn, Kerûbiyân', 'Kerûbiyân, Hamele-i Arş, Rûhânîyân', 'Kerûbiyân, Mukarrebîn, Rûhânîyân'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 19,
    "question": "Namâz Kitâbı Hakîkat Kitabevi Yayınları’nın kaç numaralı kitabıdır ?",
    "options": ['8', '9', '10', '11'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 20,
    "question": "Aşağıdakilerden hangisi Hanefi mezhebine göre guslün farzlarından birisidir ?",
    "options": ['Tertip', 'Muvalat', 'Delk', 'İstinşak'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 21,
    "question": "Bir aylık ramazan orucunun iskatı kaç altındır ?",
    "options": ['1', '5', '10', '40'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 22,
    "question": "Aşağıdakilerden hangisi Namaz Kitabında bildirilen 40 kötü huydan birisi değildir ?",
    "options": ['Müslimana kötü isim takmak', 'Mal ve mevkı hırsı', 'Müslimana beddua etmek', 'Yaptığı iyilikleri başa kakmak'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 23,
    "question": "Kaza namazları ile ilgili aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Sünnet olan namazı kazâ etmek sünnettir', 'Kaza borcu 6’dan az olana (Tertîb sâhibi) denir', 'Vâcib olan namazı kazâ etmek vâcibdir', 'Farz olan namazı kazâ etmek farzdır'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 24,
    "question": "Adak olan namâz ve başlanıp yarıda kalan nâfileler ……… namazlardır. Boşluğa gelmesi gereken ifade hangi şıkta doğru olarak verilmiştir ?",
    "options": ['Farz', 'Sünnet', 'Mübah', 'Vâcib'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 25,
    "question": "Halâya girmek için, husûsî şalvar kullanmak ve başı örtülü girmek …………. Boşluğa gelmesi gereken, hangi şıkta doğru olarak verilmiştir ?",
    "options": ['Mübahdır', 'Sünnetdir', 'Müstehabdır', 'Farzdır'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 26,
    "question": "“Farz ve vâcib namâzları, zaruret olmadıkça, hayvan üzerinde kılmak câiz değildir. Ancak, özr ile kılabilir “ Aşağıdakilerden hangisi Yukarıdaki cümlede geçen zaruri “özürler”den biri değildir ?",
    "options": ['Malının, canının, hayvanının tehlikede olması', 'Yırtıcı hayvan veya düşman olması', 'Yerin çamur olması', 'Havanın karanlık olması'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 27,
    "question": "Aşağıdaki vakitlerden hangisinde nâfile namaz kılmak mekruhtur ?",
    "options": ['Öğlenin farzından sonra', 'İkindinin farzından önce', 'Sabahın farzından sonra', 'Vitr namazından sonra'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 28,
    "question": "İmâmın, Cum'a ve Bayram namazları dışındaki her namazda; birinci rekatte, ikinci rekatte okuyacağının iki misli uzun okumasının hükmü nedir ?",
    "options": ['Mekruhtur', 'Haramdır', 'Vaciptir', 'Sünnettir'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 29,
    "question": "Aşağıdaki hallerden hangisinde secde-i sehv yapmak gerekmez ?",
    "options": ['Farzın tehirinde', 'Vacibin tehirinde', 'Vacibin terkinde', 'Birden fazla Sünnetin terkinde'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 30,
    "question": "Aşağıdakilerden hangisi namazın sünnetlerinden değildir ?",
    "options": ['Kıyamda sağ eli, sol elin üstüne koymak', 'İftitah tekbirinden sonra (sübhâneke) okumak', 'Son rekatte otururken (ettehiyyâtü) okumak', 'Selam verirken iki yanına bakmak'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 31,
    "question": "Aşağıdakilerden hangisi namazı bozan şeylerden biri değildir ?",
    "options": ['Ağızda kırâete mani olacak bir şey bulundurmak', 'Birinin selâmına başı ile cevâb vermek', 'Özrsüz, öksürmek veyâ boğazını ayıklamak', 'Namâz içinde sadece kendi işiteceği kadar gülmek'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 32,
    "question": "Aşağıdakilerden hangisi namâzın vâciblerinden değildir ?",
    "options": ['İkinci rek’atde teşehhütden fazla oturmamak', 'Son rek’atde otururken (Ettehıyyâtü) düâsını okumak.', 'Namâzda ta’dîl-i erkâna riâyet etmek', 'İftitâh tekbîrinden sonra, (Sübhâneke) okumak'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 33,
    "question": "Aşağıdakilerden hangisi namâzın sünnetlerinden biri değildir ?",
    "options": ['Namâzda gözleri yummak', 'Namâzda elleri kulağa kaldırmak', 'Tekbîr aldıkdan sonra, el bağlamak', 'Selâm verirken iki yanına bakmak'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 34,
    "question": "Aşağıdakilerden hangisi namâz bozan durumlardan biri değildir ?",
    "options": ['Namâz içinde gülmek', 'Namâz içinde inlemek ve âh etmek', 'Özrsüz, öksürmek veyâ buğazını ayıklamak', 'Farz kılarken, özrsüz dıvara ve direğe dayanmak'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 35,
    "question": "Aşağıdakilerden hangisi imam olma şartlarından biri değildir ?",
    "options": ['Bülûğ yaşında olmak', 'Akllı olmak', 'Mukim olmak', 'Müslimân olmak'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 36,
    "question": "Arapçada namaza ne denir ? ( Namaz Farsçadır)",
    "options": ['İkâme', 'Edâ', 'Salât', 'Tahiyyât'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 37,
    "question": "Aşağıdakilerden hangisi vâcib namazlardan değildir ?",
    "options": ['Bayram namazı', 'Adak olarak adanmış namaz', 'Vitr namazı', 'Cuma namazı'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 38,
    "question": "Müekked sünnet ne demektir ?",
    "options": ['Peygamberimizin nâdiren yaptığı ibâdetler', 'Peygamberimizin kuvvetle emrettiği ibâdetler', 'Peygamberimizin güzel ahlakı', 'Sünnet olup olmadığı şüpheli ibâdetler'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 39,
    "question": "Namaza başlarken “Allahü ekber” demenin hükmü nedir ?",
    "options": ['Farz', 'Vâcib', 'Müekked Sünnet', 'Müstehab'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 40,
    "question": "Aşağıdakilerden hangisi abdestin farzlarından değildir ?",
    "options": ['Yüzü bir kere yıkamak', 'Niyet etmek', 'İki ayağı birer kere yıkamak', 'Başın dörtde bir kısmını mesh etmek'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 41,
    "question": "Peygamberimizin abdestten sonra 3 defa okunması halinde peygamberler ile haşr olmaya vesîle olacağını söylediği sure hangisidir ?",
    "options": ['İhlâs suresi', 'Fâtiha suresi', 'Kadir Suresi', 'Duhâ suresi'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 42,
    "question": "Aşağıdakilerden hangisi abdestin sünnetlerinden değildir ?",
    "options": ['Yıkanacak yerleri üç kere yıkamak', 'İki kulağı mesh etmek', 'Abdeste başlarken besmele okumak', 'Yüzü yıkarken, göz pınarını, çapakları temizlemek'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 43,
    "question": "Aşağıdakilerden hangisi hanefi mezhebinde abdesti bozmaz ?",
    "options": ['Namazda uyumak', 'Sülük çok kan emerse', 'Tükürdüğünde, kan tükürükten çok olması', 'Namazda yanındaki işitecek kadar sesli gülmek'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 44,
    "question": "Cünüb kimse aşağıdakilerden hangisini yapabilir ?",
    "options": ['Kur’ân-ı kerîmi tutmak', 'Tilâvet secdesi yapmak', 'Başkasıyla müsâfaha etmek', 'Mescide girmek'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 45,
    "question": "Aşağıdakilerden hangisi hanefî mezhebinde gusül abdestinin sünnetlerinden değildir ?",
    "options": ['Bütün bedeni, üç defa oğarak yıkamak', 'Önce elleri yıkamak', 'Guslü bitirdikten sonra namaz abdesti almak', 'Niyet etmek'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 46,
    "question": "Aşağıdakilerden hangi üçünde de verilenle teyemmüm sahihtir ?",
    "options": ['Taş, Kum, Tahta', 'Taş, Kireç, Tahta', 'Toprak, Demir, Kum', 'Kum, Toprak, Kireç'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 47,
    "question": "Aşağıdakilerden hangisinde bulunanların hepsi, bir erkeğe mahremdir ?",
    "options": ['Hala, Süt Teyze, Yenge', 'Teyze, Kaynana, Amca kızı', 'Süt kız kardeşin kızı, Gelin, Hala', 'Teyze kızı, Yenge, baldız'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 48,
    "question": "Aşağıdaki vakitlerden hangisinde nâfile namaz kılmak mekruhtur ?",
    "options": ['Öğlenin farzından sonra', 'İkindinin farzından önce', 'Güneş tam tepedeyken', 'Vitr namazından sonra'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 49,
    "question": "İmâmın, Cum'a ve Bayram namazları dışındaki her namazda; birinci rekatte, ikinci rekatte okuyacağının iki misli uzun okumasının hükmü nedir ?",
    "options": ['Mekruhtur', 'Haramdır', 'Vaciptir', 'Sünnettir'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 50,
    "question": "Mızraklı İlmihâlinin asıl ismi nedir ?",
    "options": ['Nîmet-i İslam', 'Miftâhü’l- Cennet', 'Nûru’l- Îzah', 'Eyyühe’l- Veled'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 51,
    "question": "“(Miftâh-ul Cennet) ilm-i hâlinin yazarı sâlih bir zat imiş. Okuyanlara faydalı olur.” buyuran Derin İslâm âlimi kimdir ?",
    "options": ['Seyyid Abdülhakîm Arvâsî', 'Seyyid Fehîm Ârvâsî', 'Seyyid Tâhâ-i Hakkârî', 'Seyyid Abdülkâdir-i Geylânî'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 52,
    "question": "Yetmişiki bozuk fırkanın en zararlısı aşağıdakilerden hangisidir ?",
    "options": ['İsmâ\'îliyye', 'Mutezile', 'Hariciyye', 'Cebriyye'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 53,
    "question": "“Kelime-i tevhîdin sekiz ismi vardır.” Aşağıdakilerden hangisi bunlardan değildir ?",
    "options": ['Kelime-i tayyibe ', 'Dâvet-ül-Hak', 'Urvet-ül-vüska', 'Kelime-i Vera'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 54,
    "question": "Aşağıdakilerden hangisi İmam-ı A’zam hazretlerinin hocalarından değildir ?",
    "options": ['Hammad', 'İbrahim Nehâi', 'Alkama bin Kays', 'Abdullah ibni Abbas'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 55,
    "question": "Hadis-i şerifte bildirilen günahlar arasında cezası en çabuk verilecek olan günah hangisidir ?",
    "options": ['Hükümete isyan', 'Ana babaya asi olmak', 'Kul hakkı', 'Hırsızlık'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 56,
    "question": "Guslün farzları hakkında aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Hanefi mezhebinde farzı 3 tür', 'Maliki mezhebinde farzı 7 dir', 'Şafii mezhebinde 2 dir', 'Hanbeli mezhebinde 1 dir'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 57,
    "question": "Abdestin farzları hakkında aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Hanefi mezhebinde farzı 4 tür', 'Şafii mezhebinde 5 tir', 'Maliki mezhebinde farzı 7 dir', 'Hanbeli mezhebinde 6 dır'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 58,
    "question": "Altının nisabı kaç miskaldir ?",
    "options": ['10', '20', '40', '60'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 59,
    "question": "Hanefi mezhebinde tadil-i erkan farzdır buyuran alim/alimler kimdir/kimlerdir ?",
    "options": ['İmam-ı Azam', 'İmam-ı Ebû Yusuf', 'İmam-ı Muhammed', 'Tarafeyn'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 60,
    "question": "İlk minareyi kim yaptırmıştır ?",
    "options": ['Ömer bin Abdilaziz', 'Harun Reşid', 'Hazret-i Muaviye', 'Hazret-i Ömer'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 61,
    "question": "Aşağıdakilerden hangisi namazı bozanlardan değildir ?",
    "options": ['Kıyamda okuduğu rükuda tamamlamak', 'İhtiyarsız farzın birini terk etmek', 'Saçını sakalını taramak', 'Kendi imamından gayrıya feth etmek'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 62,
    "question": "Efendimiz aleyhisselam gemide namaz kılmayı kime talim buyurmuştur ?",
    "options": ['Sad bin Ebi Vakkas', 'Hazret-i Ali', 'Ebû Ubeyde bin Cerrah', 'Cafer-i Tayyar'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 63,
    "question": "Fukara-i sabirin ağniya-i şakirinden kaç yıl evvel cennete girse gerektir ?",
    "options": ['500 yıl', '550 yıl', '700 yıl', '1000 yıl'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 64,
    "question": "Aşağıdakilerden hangisi 8 cennetten birisi değildir ?",
    "options": ['Dâr-ı cemal', 'Dâr-ı karar', 'Dâr-ı selam', 'Cennet-ül-huld'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 65,
    "question": "Ahiretin bir günü dünyanın kaç senesine denk gelmektedir ?",
    "options": ['100 sene', '500 sene', '1.000 sene', '10.000 sene'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 66,
    "question": "Bir yıllık namaz ıskatının değeri kaç altındır ?",
    "options": ['7', '15', '60', '70'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 67,
    "question": "Tarafeyne göre Cuma namazı için imam efendiden gayrı kaç âdem bulunmalıdır ?",
    "options": ['2', '3', '4', '5'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 68,
    "question": "Bu ümmetten ilk terk olunan sünnet nedir ?",
    "options": ['Misvak kullanmak', 'Tebkir (Cuma namazına erken gitme)', 'Rayiha-i tayyibe', 'Sıla-i rahm'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 69,
    "question": "Aşağıdakilerden hangisi cemaate gitmemek için özür değildir ?",
    "options": ['Nadir bulunan tefsir dersini kaçırmamak', 'Havanın çok karanlık olması', 'Sevdiği yemeği kaçırmak korkusu', 'Çamur'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 70,
    "question": "İ’tikâdnâme kitabının müellifi kimdir ?",
    "options": ['İbni Âbidîn', 'İmâm Rabbanî', 'Mevlânâ Hâlid-i Bağdâdî', 'M. Hadimi'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 71,
    "question": "Aşağıdaki eşleştirmelerden hangisi yanlıştır ?",
    "options": ['Necdî-Vehhabî', 'Sünnî-Ehli Sünnet', 'Şi’i-Fırka-i Mel’une', 'Sünnî-Fırka-i Naciyye'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 72,
    "question": "Fırka-i Mel’une’nin kelime manası nedir ?",
    "options": ['Yanlış fırka', 'Lanetlenmiş fırka', 'Bidat fırkası', 'Cehennemlik fırka'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 73,
    "question": "Vehhabilere niçin fırka-i mel’une denir ?",
    "options": ['Müslümanlara kafir dedikleri için', 'Allahü teala göktedir dedikleri için', 'Kabir ziyaretine karşı oldukları için', 'Türbeleri yıktıkları için'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 74,
    "question": "Kalb ile i’tikâd edilmesi, ya’nî inanılması lâzım olan bilgilerin ilmine ne denir ?",
    "options": ['Fıkıh', 'Tasavvuf', 'Usûl-i din', 'Ahkâm-ı İslâmiyye'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 75,
    "question": "Beden ile veyâ kalb ile yapılacak ve sakınılacak ibâdet bilgilerinin ilmine ne denir ?",
    "options": ['Kelam', 'Fürû-i din', 'Akaid', 'Usûl-i fıkh'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 76,
    "question": "Peygamber efendimiz hicretten kaç sene sonra vefat ettiler ?",
    "options": ['7', '9', '10', '12'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 77,
    "question": "Kâfirler, ..... ve ..... olmak üzere ikiye ayrılır.\n\n"
        "Yukardaki boşluklara ne gelecektir ?",
    "options": ['Hrıstiyan - yahudi', 'Zararlı - zararsız', 'Mürted - zındık', 'Kitaplı - kitapsız'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 78,
    "question": "Allahü teâlâdan başka olan herşeye ne denir ?",
    "options": ['Mevcut', 'Vâcib', 'Mâsivâ', 'Haram'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 79,
    "question": "(Mümkin-ül-vücûd) için hangisi doğrudur ?",
    "options": ['Varlığı lazımdır', 'Var da olabilir, yok da olabilir', 'Var olamaz. Hep yok olması lâzımdır', 'Hiç var olmamıştır'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 80,
    "question": "(Vâcib-ül-vücûd) için aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Hep vardır', 'Önceleri ve sonsuz sonraları hiç yok olamaz', 'Yalnız Allahü teâlâ vâcib-ül-vücûddür', 'Şerîk-i bârî böyledir'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 81,
    "question": "Var olamaz. Hep yok olması lâzımdır. Şerîk-i bârî böyledir. Ya’nî, Allahü teâlâya ortak, Allahü teâlâ gibi ikinci bir tanrı var olamaz.\n\n"
        "Yukarda anlatılan kavram nedir ?",
    "options": ['Vâcib-ül-vücûd', 'Mümteni’-ul-vücûd', 'Mümkin-ül-vücûd', 'Adem'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 82,
    "question": "Hangi sıfatın manası yanlıştır ?",
    "options": ['(Hay) diri', '(Mürîd) hizmet edici', '(Basîr) görücü', '(Mütekellim) söyleyici'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 83,
    "question": "(Gözün yapısındaki nizâmı, incelikleri düşündükçe, hayretden tepem atacak gibi oluyor) diyen bilim adamı kimdir ?",
    "options": ['Lavoisier', 'Darwin', 'Dalton', 'Meyer Leksikon'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 84,
    "question": "İmam ve İslam kitabında anlatılan uzun hadîs-i şerifi hangi sahabi rivayet etmiştir ?",
    "options": ['Ebu Hureyre “radiyallahü anh”', 'Hazreti Ebu Bekir “radiyallahü anh”', 'Hazreti Ömer “radiyallahü anh”', 'Hazreti Ali “radiyallahü anh”'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 85,
    "question": "Hicretin olduğu senenin muharrem ayının birinci günü hangi takvimin sene başı kabul edildi ?",
    "options": ['Hicrî-şemsî', 'Hicrî-kamerî', 'Hicrî-rûmî', 'Miladî-şemsî'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 86,
    "question": "Aşağıdakilerden hangisi İslamiyetin beş şartından biri değildir ?",
    "options": ['Zekat vermek', 'Kurban kesmek', 'Oruç tutmak', 'Hacca gitmek'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 87,
    "question": "Hazreti Amine’nin babasının adı nedir ?",
    "options": ['İbrahim', 'Kureyş', 'Amr', 'Veheb'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 88,
    "question": "Peygamberimize peygamberliği kaç yaşında iken bildirildi ?",
    "options": ['25', '30', '33', '40'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 89,
    "question": "(Bi’set senesi) hangi seneye denir ?",
    "options": ['Dünyaya geldiği', 'Peygamberliğin bildirildiği', 'Hicretin olduğu', 'Mekke’nin fethedildiği'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 90,
    "question": "Peygamber efendimiz hicretten kaç sene sonra vefat ettiler ?",
    "options": ['7', '9', '10', '12'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 91,
    "question": "Hicretin olduğu senenin muharrem ayının birinci günü hangi takvimin sene başı kabul edildi ?",
    "options": ['Hicrî-şemsî', 'Hicrî-kamerî', 'Hicrî-rûmî', 'Miladî-şemsî'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 92,
    "question": "Toprak mahsulleri zekatına ne isim verilir ?",
    "options": ['Nisab', 'Âşir', 'Fitre', 'Uşr'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 93,
    "question": "Zekat kaç sınıf insana verilir ?",
    "options": ['4', '5', '6', '7'],
    "answer_index": 3,
  },
  {
    "questionsId": "surv_1",
    "id": 94,
    "question": "Oruçla alakalı aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Ramazana takvîmle önceden hesâb etmekle başlanır', 'Oruç tutmağa (Savm) denir.', 'Savm, lügatde, birşeyi birşeyden korumak demekdir', 'Sâim, oruç tutan kişiye denir'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 95,
    "question": "Beş vakit namaz ne zaman farz oldu ?",
    "options": ['Kadir gecesi', 'Mirac gecesi', 'Berat gecesi', 'Regaib gecesi'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 96,
    "question": "Hicretin 2. senesi hangi ibadetler farz olmuştur ?",
    "options": ['Hac ve Zekat', 'Oruç ve Hac', 'Oruç ve Zekat', 'Namaz ve Oruç'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 97,
    "question": "Hac ibadeti hicretin kaçıncı senesinde farz olmuştur ?",
    "options": ['7', '8', '9', '10'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 98,
    "question": "Erkeklerin diz ile kasıkları arası hangi mezhepte avret değildir ?",
    "options": ['Hanbeli', 'Şafii', 'Maliki', 'Hanefi'],
    "answer_index": 0,
  },
  {
    "questionsId": "surv_1",
    "id": 99,
    "question": "Allahü teâlânın (Sıfât-ı zâtiyye)si kaçtır ?",
    "options": ['5', '6', '7', '8'],
    "answer_index": 1,
  },
  {
    "questionsId": "surv_1",
    "id": 100,
    "question": "Eş’ariyye mezhebinde, ..... sıfatı, kudret sıfatı ile birdir.\n\nYukardaki boşluğa ne gelecektir ?",
    "options": ['Hayat', 'İrade', 'Tekvin', 'Vahdaniyyet'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 101,
    "question": "Melekler için aşağıdakilerden hangisi yanlıştır ?",
    "options": ['Sayısı en çok olan mahlûk meleklerdir', 'Cisimdir. Latîfdir. Gaz hâlinden de dahâ latîfdirler', 'Cehennem meleklerinin büyüğüne (Rıdvân) denir', 'Cehennem zebânîlerinin büyükleri ondokuzdur'],
    "answer_index": 2,
  },
  {
    "questionsId": "surv_1",
    "id": 102,
    "question": "Huzur-ı ilahide bulunan meleklere ne denir ?",
    "options": ['Kerûbiyân', 'Mukarrebîn', 'Rûhâniyân', 'Mübeşşir'],
    "answer_index": 1,
  },

  /*{
    "id": 1,
    "question": "s2question1",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 2,
    "question": "s2question2",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 3,
    "question": "s2question3",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 4,
    "question": "s2question4",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 5,
    "question": "s2question5",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 6,
    "question": "s2question6",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 7,
    "question": "s2question7",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 8,
    "question": "s2question8",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 9,
    "question": "s2question9",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 10,
    "question": "s2question10",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 11,
    "question": "s2question11",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 12,
    "question": "s2question12",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 13,
    "question": "s2question13",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 14,
    "question": "s2question14",
    "questionsId": "surv_2",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 1,
    "question": "s3question1",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 2,
    "question": "s3question2",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 3,
    "question": "s3question3",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 4,
    "question": "s3question4",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 5,
    "question": "s3question5",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 6,
    "question": "s3question6",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 7,
    "question": "s3question7",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 8,
    "question": "s3question8",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 9,
    "question": "s3question9",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 10,
    "question": "s3question10",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 11,
    "question": "s3question11",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 12,
    "question": "s3question12",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 13,
    "question": "s3question13",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },
  {
    "id": 14,
    "question": "s3question14",
    "questionsId": "surv_3",
    "options": ['answer1', 'answer2', 'answer3*', 'answer4'],
    "answer_index": 2,
  },*/
];
const List testQ = [ //map list, Questions and answers stored locally
  {
    "id": 1,
    "questionsId": "test",
    "question": "1",
    "options": ['1', '2', '3', '4'],
    "answer_index": 2,
  },
  {
    "id": 2,
    "questionsId": "test",
    "question": "1",
    "options": ['1', '2', '3', '4'],
    "answer_index": 2,
  },
  {
    "id": 3,
    "questionsId": "test",
    "question": "1",
    "options": ['1', '2', '3', '4'],
    "answer_index": 2,
  },
  {
    "id": 4,
    "questionsId": "test",
    "question": "1",
    "options": ['1', '2', '3', '4'],
    "answer_index": 2,
  },
];
